##
## Build with Travis.CI
##
## https://travis-ci.org/optimizationBenchmarking/utils-graphics
#
# The basic utility classes of the optimizationBenchmarking.org tool chain
# are a Java 7.0 Project.
language: java

# By default, it runs under Java 7
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
    
# Cache Maven dependencies to speed up builds.
cache:
  directories:
  - $HOME/.m2

# custom build step
script: ant

before_install:
# Install ant 1.9.6 as described at
# http://www.askubuntu.com/questions/674328/
  - sudo apt-get -y purge ant
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.gz
  - tar -xvzf apache-ant-1.9.6-bin.tar.gz
  - sudo mv apache-ant-1.9.6 /opt/
  - rm -f apache-ant-1.9.6-bin.tar.gz
  - sudo ln -s /opt/apache-ant-1.9.6/bin/ant /usr/bin/ant
  - echo "export ANT_HOME=\"/opt/apache-ant-1.9.6\"" >> ~/.bashrc
  - echo "export ANT_OPTS=\"-Xmx2048m -XX:MaxPermSize=1024m\"" >> ~/.bashrc
# fix for buffer overflows in getLocalHostName
# https://github.com/travis-ci/travis-ci/issues/5227
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*
  
# prevent Maven from running
install:
  - echo "Nothing."